version: 0.2
            
phases:
  install:
    commands:
      - echo Installing node.js...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      - curl -L https://npmjs.org/install.sh | sh
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - node routes.js

artifacts:
  files:
    - */**
  discard-paths: no
